version: "3.2"

services:
  static:
    image: nginx:stable
    container_name: django_sample_static
    ports:
      - "8000:80"
    volumes:
      - sample_static_data:/var/www/static
      - ./conf:/etc/nginx/conf.d
    env_file:
      - sample/.env
    networks:
      django_sample_net:
        aliases:
          - django_sample_static

  app:
    build:
      context: .
    container_name: django_sample_app
    expose:
      - 8000
    volumes:
      - sample_static_data:/opt/sample/static
      - sample_app_data:/opt/sample/data
    env_file:
      - sample/.env
    networks:
      django_sample_net:
        aliases:
          - django_sample_app

networks:
  django_sample_net:

volumes:
  sample_static_data:
  sample_app_data:
